model_class: iTransformer

# List of masks
masker: 
  neuron:
    force_active: true         
    mode: neuron      # masking mode
    ratio: 0.1          # ratio of data to predict
    zero_ratio: 1.0     # of the data to predict, ratio of zeroed out
    random_ratio: 1.0   # of the not zeroed, ratio of randomly replaced
    expand_prob: 0.0    # probability of expanding the mask in ``temporal`` mode
    max_timespan: 1     # max span of mask if expanded
    channels: null
    mask_regions: null       # brain regions to mask in ``inter-region`` mode
    target_regions: null    # brain regions to predict in ``intra-region`` mode
    n_mask_regions: 1       # number of regions to choose from the list of mask_regions or target_regions
  temporal: 
    force_mode: temporal      # masking mode
    ratio: 0.1          # ratio of data to predict
    zero_ratio: 1.0     # of the data to predict, ratio of zeroed out
    random_ratio: 1.0   # of the not zeroed, ratio of randomly replaced
    expand_prob: 0.0    # probability of expanding the mask in ``temporal`` mode
    max_timespan: 1     # max span of mask if expanded
    channels: null
    mask_regions: null       # brain regions to mask in ``inter-region`` mode
    target_regions: null    # brain regions to predict in ``intra-region`` mode
    n_mask_regions: 1       # number of regions to choose from the list of mask_regions or target_regions


encoder:
  from_pt: null

  embedder:
    bias: true
    activation: relu
    dropout: 0.2
    max_n_bins: 50

  hidden_size: 768
  activation: relu
  bias: true
  dropout: 0.4
  n_heads: 8
  n_layers: 5
  max_n_channels: 1500 # 0 to skip channel embeddings
  embed_region: true
  neuron_regions: null       # set this to the list of all regions in the dataset before initialisation


decoder:
  from_pt: null
  mlp_decoder: true
  activation: relu
  use_cls: true
