seed: 42

savestring: test
wandb_project: test
log_to_wandb: false

verbosity: 0

# wandb configuration
wandb:
  use: true
  entity: null
  project: test
  run_name: ndt1-ssl

# Logging directories
dirs:
  checkpoint_dir: checkpoints  # save model state dicts (todo optimizer states)
  log_dir: results  # save tensorboard logs
  dataset_cache_dir: checkpoints/datasets_cache
  dataset_dir: /home/ppwang/neural-data-transformers/data/lfads_lorenz.h5
  


# Training configuration
training:
  num_epochs: 200
  train_batch_size: 32
  test_batch_size: 256  
  shuffle_test_dataloader: false    # Shuffle test dataloader between epochs

  save_every: null  # Save checkpoint
  eval_every: null  # Eval model



# Model configuration. 
# Will be passed to the model __init__  method if a model is not passed to the Trainer __init__ method.
model: 
  model_class: null   # Any registered model class name. 

# Data configuration.
data:
  dataset_name: lorenz # Any registered dataset name.
  dataset_class: ssl # Any registered dataset class name. 

  # Load raw dataset if a dataset is not passed to the Trainer __init__ method. 
  hf_dataset_name: null   # from huggingface
  json_dataset_name: null # from json file

  train_name: train   # name of the train split in the raw datasete
  test_name: test     # name of the test split in the raw datasete
  train_len: null     # used length of the train dataset. null to use all
  test_len: null      # used length of the test dataset. null to use all

  LOG_EPSILON: 1.e-7 # epsilon for log transformation, to prevent log(0)
  use_lograte: True # use lograte

  max_seq_len: 50 # max sequence length


# Method configuration. Contains kwargs that are specific to the training method.
method:

  # Passed to the model __init__ method together with the model config
  model_kwargs: 
    method_name: ssl

    use_lograte: true
    loss: poisson_nll # mse/other distirbutions (todo)

  # Passed to the Dataset __init__ method together with the raw dataset. 
  dataset_kwargs: {}

  # Passed to the DataLoader __init__ method.
  dataloader_kwargs:
    # Contains which keys to pad, along which dimension with which value
    pad_dict: 
      spikes:
          dim: 0
          side: right
          value: 0
          truncate: null
          min_length: null
      

optimizer:
  gradient_accumulation_steps: 1
  lr: 1.e-4
  wd: 0.01
  eps: 1.e-8
  warmup_pct: 0.15 # cosine/linear
  gamma: 0.95     # step
  div_factor: 10  # cosine
  scheduler: cosine # step/cosine/linear