seed: 42

savestring: test
wandb_project: iTransformer_multi
log_to_wandb: false

verbosity: 0

# wandb configuration
wandb:
  use: True
  entity: wdk0082
  project: iTransformer_multi
  run_name: test_30_neuron_ratio=0.1

# Logging directories
dirs:
  log_dir: /expanse/lustre/scratch/zwang34/temp_project/iTransformer/checkpoints/test_30_neuron_ratio=0.1 # save models
  dataset_cache_dir: /expanse/lustre/scratch/zwang34/temp_project/iTransformer/checkpoints/datasets_cache  # save dataset cache
  dataset_dir: neurofm123/671c7ea7-6726-4fbe-adeb-f89c2c8e489b_aligned # not used in multi-session training.
  huggingface_org: neurofm123
  # checkpoint_dir: /mnt/home/yzhang1/ceph/checkpoints  # save model state dicts (todo optimizer states)
  # dataset_dir: /home/ppwang/neural-data-transformers/data/lfads_lorenz.h5
  # behav_dir:  /home/exouser/Documents/IBL_foundation_model/data/671c7ea7-6726-4fbe-adeb-f89c2c8e489b_aligned
  # pretrained_model_path: checkpoints/models/ndt1/ssl/temporal/model_best_multi-session.pt


# Training configuration
training:
  num_epochs: 500
  train_batch_size: 32
  test_batch_size: 128  
  shuffle_test_dataloader: false    # Shuffle test dataloader between epochs

  save_plot_every_n_epochs: 5  # Plot the model output every n epochs
  save_every: 30  # Save checkpoint
  eval_every: null  # Eval model



# Model configuration. 
# Will be passed to the model __init__  method if a model is not passed to the Trainer __init__ method.
model: 
  model_class: iTransformer   # Any registered model class name.

# Data configuration.
data:
  # dataset_name: lorenz # Any registered dataset name.
  dataset_name: ibl # Any registered dataset name.
  dataset_class: ssl # Any registered dataset class name.

  # Load raw dataset if a dataset is not passed to the Trainer __init__ method. 
  hf_dataset_name: null   # from huggingface
  json_dataset_name: null # from json file

  train_name: train   # name of the train split in the raw datasete
  test_name: test     # name of the test split in the raw datasete
  train_len: null     # used length of the train dataset. null to use all
  test_len: null      # used length of the test dataset. null to use all

  LOG_EPSILON: 1.e-7 # epsilon for log transformation, to prevent log(0)
  use_lograte: True # use lograte

  max_time_length: 100    # max_time_length has to be a multiple of time patch size
  max_space_length: 600   # max_space_length has to be a multiple of space patch size
  patching: false # patching the neurons
  sort_by_depth: false
  sort_by_region: false
  brain_region: all
  spike_augmentation: false

  include_behav: false # include behavior data
  target: null

  load_meta: true

  num_sessions: 3
  test_session_eid: ["671c7ea7-6726-4fbe-adeb-f89c2c8e489b"] 

  split_method: session_based # random_split/session_based

  use_aligned_test: False

# Method configuration. Contains kwargs that are specific to the training method.
method:

  # Passed to the model __init__ method together with the model config
  model_kwargs: 
    method_name: ssl #ssl 

    use_lograte: true
    loss: poisson_nll  # poisson_nll # mse/other distirbutions (todo)
    output_size: 2
    clf: false
    reg: false

  # Passed to the Dataset __init__ method together with the raw dataset. 
  dataset_kwargs: {}

      

optimizer:
  gradient_accumulation_steps: 1
  lr: 1.e-4
  wd: 0.01
  eps: 1.e-8
  warmup_pct: 0.15 # cosine/linear
  gamma: 0.95     # step
  div_factor: 10  # cosine
  scheduler: cosine # step/cosine/linear
